[phases.setup]
nixPkgs = ["nodejs-18_x", "npm"]

[phases.install]
cmds = [
  "cd backend && npm ci",
  "cd frontend && npm ci && npm run build"
]

[phases.build]
cmds = []

[start]
cmd = "cd backend && npm start"

